# Generated by Django 5.2.17 on 2026-08-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Certificate / Compliance Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description / Authority"
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="certificates/",
                        verbose_name="Certificate File / Image",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(blank=True, null=True, verbose_name="Issue Date"),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="Expiry Date"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only active certificates will be displayed publicly",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Certificate",
                "verbose_name_plural": "Certificates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Full Name")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Company Name",
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        max_length=30, verbose_name="Mobile / Phone Number"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        max_length=100, verbose_name="Country / Destination Port"
                    ),
                ),
                (
                    "product",
                    models.CharField(
                        choices=[
                            ("Raw Tobacco Leaf", "Raw Tobacco Leaf"),
                            ("Moringa Leaf Powder", "Moringa Leaf Powder"),
                            (
                                "General / Other Sourcing Inquiry",
                                "General / Other Sourcing Inquiry",
                            ),
                        ],
                        default="Raw Tobacco Leaf",
                        max_length=120,
                        verbose_name="Product of Interest",
                    ),
                ),
                (
                    "product_details",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Requirements / Quantity / Specifications",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Additional Remarks / Timeline",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("READ", "Read"),
                            ("CONTACTED", "Contacted"),
                            ("CLOSED", "Closed"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal notes for administrators",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Inquiry",
                "verbose_name_plural": "Inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Product name, e.g. Raw Tobacco Leaf",
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "botanical_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Botanical name if applicable, e.g. Moringa oleifera",
                        max_length=200,
                    ),
                ),
                (
                    "part_used",
                    models.CharField(
                        blank=True, default="", help_text="e.g. Leaves", max_length=100
                    ),
                ),
                ("origin", models.CharField(default="India", max_length=100)),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Short product highlight",
                        max_length=255,
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        help_text="Concise description for homepage and listing cards"
                    ),
                ),
                (
                    "overview",
                    models.TextField(help_text="Detailed overview of the product"),
                ),
                (
                    "key_highlights",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Newline-separated list of key highlights",
                    ),
                ),
                (
                    "sourcing_details",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Information about Indian origin and sourcing consistency",
                    ),
                ),
                (
                    "quality_parameters",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Quality, grade, and buyer-specific handling",
                    ),
                ),
                (
                    "packaging_details",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Bulk export packaging information",
                    ),
                ),
                (
                    "applications",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="End-use and industry applications",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Product main image", upload_to="products/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["display_order", "name"],
            },
        ),
    ]
